maintainer        "CrowdMob Inc."
maintainer_email  "developers@crowdmob.com"
license           "Apache 2.0"
description       "Install CrowdMob's kafka-s3-consumer, configure with deployed apps, and run with monit."
version           "0.0.1"
recipe            "kafka-s3-consumer::install"
recipe            "kafka-s3-consumer::run"
depends           "golang"
depends           "monit"
depends           "deploy"
